export const ANIMAL_LIST = [
    { id: 1, name: 'Carnero', emoji: '🐏', color: '#FFD700', imageSelector: '/animals/1.jpg', imageWheel: '/animals/1.png', sound: '/sounds/win1.mp3' },
    { id: 2, name: 'Toro', emoji: '🐂', color: '#8B4513', imageSelector: '/animals/2.jpg', imageWheel: '/animals/2.png', sound: '/sounds/win2.mp3' },
    { id: 3, name: 'Cienpies', emoji: '🐛', color: '#9ACD32', imageSelector: '/animals/3.jpg', imageWheel: '/animals/3.png', sound: '/sounds/win3.mp3' },
    { id: 4, name: 'Alacrán', emoji: '🦂', color: '#DC143C', imageSelector: '/animals/4.jpg', imageWheel: '/animals/4.png', sound: '/sounds/win4.mp3' },
    { id: 5, name: 'León', emoji: '🦁', color: '#FFD700', imageSelector: '/animals/5.jpg', imageWheel: '/animals/5.png', sound: '/sounds/win5.mp3' },
    { id: 6, name: 'Rana', emoji: '🐸', color: '#32CD32', imageSelector: '/animals/6.jpg', imageWheel: '/animals/6.png', sound: '/sounds/win6.mp3' },
    { id: 7, name: 'Perico', emoji: '🦜', color: '#00CED1', imageSelector: '/animals/7.jpg', imageWheel: '/animals/7.png', sound: '/sounds/win7.mp3' },
    { id: 8, name: 'Ratón', emoji: '🐭', color: '#708090', imageSelector: '/animals/8.jpg', imageWheel: '/animals/8.png', sound: '/sounds/win8.mp3' },
    { id: 9, name: 'Águila', emoji: '🦅', color: '#CD853F', imageSelector: '/animals/9.jpg', imageWheel: '/animals/9.png', sound: '/sounds/win9.mp3' },
    { id: 10, name: 'Tigre', emoji: '🐯', color: '#FFA500', imageSelector: '/animals/10.jpg', imageWheel: '/animals/10.png', sound: '/sounds/win10.mp3' },
    { id: 11, name: 'Gato', emoji: '🐱', color: '#FFA07A', imageSelector: '/animals/11.jpg', imageWheel: '/animals/11.png', sound: '/sounds/win11.mp3' },
    { id: 12, name: 'Caballo', emoji: '🐴', color: '#8B4513', imageSelector: '/animals/12.jpg', imageWheel: '/animals/12.png', sound: '/sounds/win12.mp3' },
    { id: 13, name: 'Mono', emoji: '🐵', color: '#DEB887', imageSelector: '/animals/13.jpg', imageWheel: '/animals/13.png', sound: '/sounds/win13.mp3' },
    { id: 14, name: 'Paloma', emoji: '🕊️', color: '#F5F5F5', imageSelector: '/animals/14.jpg', imageWheel: '/animals/14.png', sound: '/sounds/win14.mp3' },
    { id: 15, name: 'Zorro', emoji: '🦊', color: '#FF8C00', imageSelector: '/animals/15.jpg', imageWheel: '/animals/15.png', sound: '/sounds/win15.mp3' },
    { id: 16, name: 'Oso', emoji: '🐻', color: '#8B4513', imageSelector: '/animals/16.jpg', imageWheel: '/animals/16.png', sound: '/sounds/win16.mp3' },
    { id: 17, name: 'Pavo', emoji: '🦃', color: '#8B0000', imageSelector: '/animals/17.jpg', imageWheel: '/animals/17.png', sound: '/sounds/win17.mp3' },
    { id: 18, name: 'Burro', emoji: '🫏', color: '#A9A9A9', imageSelector: '/animals/18.jpg', imageWheel: '/animals/18.png', sound: '/sounds/win18.mp3' },
    { id: 19, name: 'Chivo', emoji: '🐐', color: '#D2B48C', imageSelector: '/animals/19.jpg', imageWheel: '/animals/19.png', sound: '/sounds/win19.mp3' },
    { id: 20, name: 'Cerdo', emoji: '🐷', color: '#FFC0CB', imageSelector: '/animals/20.jpg', imageWheel: '/animals/20.png', sound: '/sounds/win20.mp3' },
    { id: 21, name: 'Gallo', emoji: '🐓', color: '#FF4500', imageSelector: '/animals/21.jpg', imageWheel: '/animals/21.png', sound: '/sounds/win21.mp3' },
    { id: 22, name: 'Camello', emoji: '🐪', color: '#F5DEB3', imageSelector: '/animals/22.jpg', imageWheel: '/animals/22.png', sound: '/sounds/win22.mp3' },
    { id: 23, name: 'Cebra', emoji: '🦓', color: '#FFFFFF', imageSelector: '/animals/23.jpg', imageWheel: '/animals/23.png', sound: '/sounds/win23.mp3' },
    { id: 24, name: 'Iguana', emoji: '🦎', color: '#556B2F', imageSelector: '/animals/24.jpg', imageWheel: '/animals/24.png', sound: '/sounds/win24.mp3' },
    { id: 25, name: 'Gallina', emoji: '🐔', color: '#FF6347', imageSelector: '/animals/25.jpg', imageWheel: '/animals/25.png', sound: '/sounds/win25.mp3' },
    { id: 26, name: 'Vaca', emoji: '🐄', color: '#F0F8FF', imageSelector: '/animals/26.jpg', imageWheel: '/animals/26.png', sound: '/sounds/win26.mp3' },
    { id: 27, name: 'Perro', emoji: '🐕', color: '#87CEFA', imageSelector: '/animals/27.jpg', imageWheel: '/animals/27.png', sound: '/sounds/win27.mp3' },
    { id: 28, name: 'Buitre', emoji: '🦅', color: '#2F4F4F', imageSelector: '/animals/28.jpg', imageWheel: '/animals/28.png', sound: '/sounds/win28.mp3' },
    { id: 29, name: 'Elefante', emoji: '🐘', color: '#D3D3D3', imageSelector: '/animals/29.jpg', imageWheel: '/animals/29.png', sound: '/sounds/win29.mp3' },
    { id: 30, name: 'Cocodrilo', emoji: '🐊', color: '#006400', imageSelector: '/animals/30.jpg', imageWheel: '/animals/30.png', sound: '/sounds/win30.mp3' },
    { id: 31, name: 'Hamster', emoji: '🐹', color: '#FFE4B5', imageSelector: '/animals/31.jpg', imageWheel: '/animals/31.png', sound: '/sounds/win31.mp3' },
    { id: 32, name: 'Ardilla', emoji: '🐿️', color: '#CD853F', imageSelector: '/animals/32.jpg', imageWheel: '/animals/32.png', sound: '/sounds/win32.mp3' },
    { id: 33, name: 'Pez', emoji: '🐠', color: '#00BFFF', imageSelector: '/animals/33.jpg', imageWheel: '/animals/33.png', sound: '/sounds/win33.mp3' },
    { id: 34, name: 'Venado', emoji: '🦌', color: '#D2691E', imageSelector: '/animals/34.jpg', imageWheel: '/animals/34.png', sound: '/sounds/win34.mp3' },
    { id: 35, name: 'Jirafa', emoji: '🦒', color: '#FFFFE0', imageSelector: '/animals/35.jpg', imageWheel: '/animals/35.png', sound: '/sounds/win35.mp3' },
    { id: 36, name: 'Culebra', emoji: '🐍', color: '#9ACD32', imageSelector: '/animals/36.jpg', imageWheel: '/animals/36.png', sound: '/sounds/win36.mp3' }
];
