-- Migration 026: Add ticket customization and security settings
ALTER TABLE public.venue_settings
ADD COLUMN IF NOT EXISTS ticket_header TEXT DEFAULT 'RULETA VIRTUAL',
ADD COLUMN IF NOT EXISTS ticket_subheader TEXT DEFAULT 'VALDIVIA 2026',
ADD COLUMN IF NOT EXISTS ticket_terms_line1 TEXT DEFAULT 'CANJEA EN TU CELULAR',
ADD COLUMN IF NOT EXISTS ticket_terms_line2 TEXT DEFAULT 'PRESENTA ESTE TICKET SI GANAS',
ADD COLUMN IF NOT EXISTS max_failed_attempts INTEGER DEFAULT 3,
ADD COLUMN IF NOT EXISTS cooldown_minutes INTEGER DEFAULT 5;
